# Custom build version
version: 0.{build}-{branch}

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"

# Don't finish after first fail
matrix:
  fast_finish: false

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Install PhantomJS
  - cinst PhantomJS
  - set path=%path%;C:\tools\PhantomJS\
  - dir C:\tools\PhantomJS
  # Typical npm stuff.
  - md C:\nc
  - npm install -g npm@^2
  # Workaround https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set cache C:\nc
  - npm version
  - ps: cd C:\projects\misago\misago\emberapp
  - npm install -g bower
  - npm install
  - bower install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
