name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up PostgreSQL 11
        run: |
          sudo apt-get install wget ca-certificates
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          RELEASE=$(lsb_release -cs)
          echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-11
          echo "================================"
          sudo -u postgres psql -c "CREATE USER misago WITH ENCRYPTED PASSWORD 'misago';"
          sudo -u postgres createdb misago -O misago
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Test with pytest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          MISAGO_DATABASE_URL: postgresql://localhost/misago?user=misago&password=misago
          MISAGO_CACHE_URL: locmem://0
          MISAGO_STATIC_ROOT: /app/media
          MISAGO_MEDIA_ROOT: /app/static
        run: |
          pytest --cov=misago
          coveralls
